#pragma config(Sensor, S1,     boton,          sensorEV3_Touch)
#pragma config(Motor,  motorA,          m,             tmotorEV3_Medium, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

while(true){
	if(getTouchValue(boton)==1){
		setMotorSpeed(m,50);

	}

	else{
		setMotorSpeed(m,0);

	}
}

}
