#pragma config(Sensor, S1,     der,            sensorEV3_Touch)
#pragma config(Sensor, S2,     izq,            sensorEV3_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){
		int d = getTouchValue(der);
		int i = getTouchValue(izq);
		if(d==1){
			setMotorSpeed(motorA,70);
			setMotorSpeed(motorB,-70);
		}

		if(i==1){
			setMotorSpeed(motorB,70);
			setMotorSpeed(motorA,-70);
		}
		else{
			setMotorSync(motorA,motorB,0,80);
		}
	}
}
