
#pragma config(Motor,  motorA,          DERECHO,       tmotorEV3_Large, openLoop)
#pragma config(Motor,  motorB,          izquierdo,     tmotorEV3_Large, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
setMotorSpeed (motorA, 100);
setMotorSpeed (motorB, 100);
delay(500);
setMotorSpeed (motorA, -100);
setMotorSpeed (motorB, 100);
delay(255);
setMotorSpeed (motorA, 100);
setMotorSpeed (motorB, 100);
delay(850);
setMotorSpeed (motorA, 100);
setMotorSpeed (motorB, -100);
delay(285);
setMotorSpeed (motorA, 100);
setMotorSpeed (motorB, 100);
delay(1800);
setMotorSpeed (motorA, -100);
setMotorSpeed (motorB, 100);
delay(255);
setMotorSpeed (motorA, 100);
setMotorSpeed (motorB, 100);
delay(900);
setMotorSpeed (motorA, 100);
setMotorSpeed (motorB, -100);
delay(285);
setMotorSpeed (motorA, 100);
setMotorSpeed (motorB, 100);
delay(950);
setMotorSpeed (motorA, 100);
setMotorSpeed (motorB, -100);
delay(255);
setMotorSpeed (motorA, 100);
setMotorSpeed (motorB, 100);
delay(1250);
setMotorSpeed (motorA, -100);
setMotorSpeed (motorB, 100);
delay(255);
setMotorSpeed (motorA, 100);
setMotorSpeed (motorB, 100);
delay(500);

}
