#pragma config(Motor,  motorA,          derecho,       tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          izquierdo,     tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	setMotorSync(motorA,motorB,0,50);
	delay(700);
	setMotorSpeed(derecho,100);
	setMotorSpeed(izquierdo,0);
	delay(700);
	setMotorSync(derecho,izquierdo,0,-50);
	delay(900);
	setMotorSpeed(izquierdo,-100);
	setMotorSpeed(derecho,0);
	delay(600);
	setMotorSync(derecho,izquierdo,0,-50);
	delay(1000);
	setMotorSpeed(izquierdo,100);
	setMotorSpeed(derecho,0);
	delay(500);
	setMotorSync(derecho,izquierdo,0,-50);
	delay(1400);
	setMotorSpeed(derecho,100);
	setMotorSpeed(izquierdo,0);
	delay(500);
	setMotorSync(derecho,izquierdo,0,-50);
	delay(700);
	setMotorSpeed(derecho,-25);
	setMotorSpeed(izquierdo,0);
	delay(1200);
}
