#pragma config(Sensor, S1,     bd,             sensorEV3_Touch)
#pragma config(Sensor, S2,     bi,             sensorEV3_Touch)
#pragma config(Motor,  motorA,          m,             tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          s,             tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){
		setMotorSpeed(m,70);

		if(getTouchValue(bd)==1){
			setMotorSpeed(s,40);
		}
		if(getTouchValue(S2)==1){
			setMotorSpeed(s,-40);

		}
	}
}
