


#pragma config(Motor,  motorA,          A,             tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          B,             tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){


setMotorSync(A,B,0,100);
delay(800);
setMotorSpeed(A,-100);
setMotorSpeed(B,100);
delay(350);
setMotorSync(A,B,0,100);
delay(800);
setMotorSpeed(A,100);
setMotorSpeed(B,-100);
delay(350);
setMotorSync(A,B,0,100);
delay(800);
setMotorSpeed(A,-100);
setMotorSpeed(B,100);
delay(300);
setMotorSync(A,B,0,100);
delay(700);
setMotorSpeed(A,100);
setMotorSpeed(B,-100);
delay(400);
setMotorSync(A,B,0,100);
delay(1100);
setMotorSpeed(A,100);
setMotorSpeed(B,-100);
delay(200);
setMotorSync(A,B,0,100);
delay(800);
setMotorSpeed(A,-100);
setMotorSpeed(B,100);
delay(350);
setMotorSync(A,B,0,100);
delay(1000);
setMotorSpeed(A,100);
setMotorSpeed(B,-100);
delay(350);
setMotorSync(A,B,0,100);
delay(600);
setMotorSpeed(A,-100);
setMotorSpeed(B,100);
delay(350);
setMotorSync(A,B,0,100);
delay(1200);
setMotorSpeed(A,-100);
setMotorSpeed(B,100);
delay(200);
setMotorSync(A,B,0,100);
delay(800);

}
