#pragma config(Sensor, S1,     u,              sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          g,             tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){
		if(getUSDistance(u)<10){
			setMotorTarget(g,45,50);
			waitUntilMotorStop(g);
			delay(5000);
			setMotorTarget(g,0,50);
			waitUntilMotorStop(g);
		}
		else{
			setMotorSpeed(g,0);
		}
	}
}
